config/routes.rb
Rails.application.routes.draw do 
  
  root to: 'users#index'

  resources :groups
  resources :events do
  	get 'join', to: 'events#join_event'
  end
  
  get 'user/my_events', to: 'users#my_events'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'newevent', to: 'events#new'
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :participants
  has_many :users, through: :participants

  geocoded_by :address
  after_validation :geocode, if: ->(obj) { obj.address.present? && obj.address_changed? }

  scope :where_participating, ->(user) { joins(:participants).where('participants.user_id': user) }

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @lat = @event.latitude
    @lng = @event.longitude
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(
      event_params.merge(owner_id: current_user.id)
    )

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def join_event
    @event = Event.find(params[:event_id])

    participant = @event.participants.build(user_id: current_user.id)

    respond_to do |format|
      format.html { redirect_to @event, notice: 'You joined this event.' } if participant.save
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:name, :description, :latitude, :longitude, :address, :date, :time)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event_feed.html.erb
<ul id ="event-feed">
    <% Event.all.each do |event| %>
      <li>
      	<span><%= event.name %>, <%= event.address %> </br> <%= event.date %>, <%= event.time.strftime("%I:%M%p") %></span><br/>
      	<span><%= link_to 'Sign Up!', event_join_path(event) %></span>
      </li>
    <% end %>
</ul>

app/views/events/_form.html.erb
<div class="form-control">
  <div class="row">
    <div class="sidenav" id="login-field">
      <div class="field form-control" >


      <%= form_with(model: event, local: true) do |form| %>
        <% if event.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

            <ul>
            <% event.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= form.label :name %><br />
          <%= form.text_field :name, id: :event_name%>
        </div>

        <div class="field">
          <%= form.label :description %><br />
          <%= form.text_field :description, id: :event_description %>
        </div>

        <div class="field">
          <%= form.label :address %><br />
          <%= form.text_field :address, id: :event_address %>
          <p> Format: Wojskowa 6, Poznań </p>
        </div>

        <div class="field">
          <%= form.label :date %><br />
          <%= form.date_field :date, id: :event_date %>
        </div>

        <div class="field">
          <%= form.label :time %><br />
          <%= form.time_field :time, id: :event_time %>
        </div>

        <div class="actions">
          <%= form.submit class: "btn btn-outline-secondary"%>
        </div>
      <% end %>


      </div>
    </div>
  </div>
</div>

app/views/events/_map.html.erb
<div id="map", data-lat="<%= @lat %>" data-lng="<%= @lng %>" ></div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.description %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Event', newevent_path%>

app/views/events/my_events.html.erb
<h3>My Events</h3>
<ul id ="event-feed">
    <% Event.all.where(owner_id: current_user.id).each do |event| %>
      <li>
      	<span><%= event.name %>, <%= event.address %> </br> <%= event.date %>, <%= event.time.strftime("%I:%M%p") %></span><br/>
      </li>
    <% end %>
</ul>

<!-- <h3></h3>
<ul id ="event-feed">
    <% Event.where_participating(current_user).each do |event| %>
      <li>
      	<span><%= event.name %>, <%= event.address %> </br> <%= event.date %>, <%= event.time.strftime("%I:%M%p") %></span><br/>
      </li>
    <% end %>
</ul> -->

app/views/events/new.html.erb
<!-- <h1>New Event</h1> -->

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<% if @event.participants.map(&:id).include?(current_user.id) %>
  <p style="font-size:18px"> You are going to this event. </p>
<% end %>

<p>
  <%= render "events/map" %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>