config/routes.rb
Rails.application.routes.draw do 
  
  root to: 'users#index'

  resources :groups
  resources :events do
  	get 'join', to: 'events#join_event'
  end
  
  get 'user/my_events', to: 'users#my_events'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'newevent', to: 'events#new'
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">

    <div class="form-inline" id="log">
      <div>
        <% if current_user %>
          <span id="user-name">
            <%= current_user.first_name %>
          </span>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
        <% else %>
          <span id ="app-name">NomadApp</span>
        <% end %>
      </div>

      <form class="form-inline">
        <div id="nav-button2">
          <%= link_to "Add Event", new_event_path %>
        </div>

        <div id="nav-button3">
          <%= link_to "My Events", user_my_events_path %>
        </div>

        <div id="nav-button1">
          <%= link_to "Home", root_path %>
        </div>
      </form>

    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NomadApp</title>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyCu9cIDuY72J2pJxd482dU9S6GXlNdVHzA&callback" %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <%= render "layouts/nav"%>
      <%= yield %>
    </div>
  </body>
</html>